name: LOVE LIFE NUTRITION
favicon: null
layout_spectrum: 0.36054605012759566
typography_spectrum: 0.6901659620925784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5943664917722344
  lightness: 0.5070176189765334
  saturation: 0.44174466095864773
  rhythmicContrast: 0.7467302249278873
purpose: []
